---

- name: Check if user exists
  getent:
    database: passwd
    key: "{{ user_dict.name }}"
    fail_key: no
  when:
  - user_dict.name is defined

- name: Create user
  user:
    name: "{{ user_dict.name }}"
    comment: "{{ user_dict.comment }}"
    state: present
    shell: /bin/bash
    groups: "{{ user_dict.groups }}"
    append: yes
  register: created_user
  when:
  - user_dict.name is defined
  - user_dict.comment is defined

- name: Remove the blank password for the user
  command: "passwd -d {{ user_dict.name }}"
  when:
  - getent_passwd[user_dict.name] == None
  - created_user.changed

- name: Force change password
  command: "chage -d 0 {{ user_dict.name }}"
  when:
  - getent_passwd[user_dict.name] == None
  - created_user.changed

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ user_dict.name }}"
    state: present
    key: "{{ item }}"
  loop: "{{ user_dict.public_keys }}"
  when:
  - user_dict.name is defined
  - user_dict.comment is defined
  - user_dict.public_keys is defined
