stages:
  - build
  - provision

Build Base Image:
  stage: build
  tags:
    - msul-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  image: docker:19.03
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build  -t $CI_REGISTRY_IMAGE/ansible:latest --cache-from $CI_REGISTRY_IMAGE/ansible:latest .
    - docker push $CI_REGISTRY_IMAGE/ansible:latest

Provision:
  stage: provision
  tags:
    - msul-docker
  image: $CI_REGISTRY_IMAGE/ansible:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  variables:
    TZ: America/Detroit
  before_script:
    # Setting up ssh key
    - eval $( ssh-agent -s )
    - echo "$ANSIBLE_PRIVATE_KEY" | base64 -d | ssh-add -
    - install -d -m 700 ~/.ssh/
    - ( umask 022; touch ~/.ssh/known_hosts )
  script:
    # Run the playbooks to provision and configure
    - cat provision-playbook/variables.yml | envsubst | sponge provision-playbook/variables.yml
    - ansible-playbook provision-playbook/provision.yml
    - ansible-playbook configure-playbook/configure.yml -i configure-playbook/hosts
    - echo "Success! Servers are now accessible with the following IPs"
    - cat configure-playbook/hosts
