stages:
  - provision

Provision:
  stage: provision
  tags:
    - msul-docker
  image: ubuntu:22.04
  variables:
    TZ: America/Detroit
  before_script:
    - apt update
    - apt install software-properties-common -y
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo $TZ > /etc/timezone
  script:
    - add-apt-repository --yes --update ppa:ansible/ansible
    - apt install moreutils gettext-base ansible -y
    - ansible-galaxy collection install community.general ansible.posix
    - envsubst provision-playbook/variables.yml | sponge provision-playbook/variables.yml
    - ansible-playbook provision-playbook/provision.yml
