stages:
  - test
  - build
  - shared
  - devel
  - prod
  - optional

variables:
  TZ: America/Detroit

Shellcheck:
  stage: test
  image: alpine:latest
  timeout: 5m
  tags:
    - msul-shared
  interruptible: true
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  before_script:
    - apk add shellcheck || apt install shellcheck
  script:
    - shellcheck $(find . -name "*.sh" -o -name "*pc-*" -not -path "./.git/*")

kics-iac-sast:
  tags:
    - msul-shared

secret_detection:
  tags:
    - msul-shared

Build Base Image:
  stage: build
  tags:
    - msul-shared
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  image: docker:19.03
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build  -t $CI_REGISTRY_IMAGE/ansible:latest --cache-from $CI_REGISTRY_IMAGE/ansible:latest .
    - docker push $CI_REGISTRY_IMAGE/ansible:latest

Provision Shared Resources:
  extends: .provision_template
  stage: shared
  environment:
    name: shared
  variables:
    TERRAFORM_ENV: shared
  artifacts:
    paths:
      - terraform.tfvars.json

1-Provision Devel Cluster:
  extends: .provision_template
  stage: devel
  environment:
    name: devel
  variables:
    TERRAFORM_ENV: devel

2-Configure Devel Cluster:
  extends: .configure_template
  stage: devel
  environment:
    name: devel
  needs:
    - job: Provision Shared Resources
      artifacts: true
    - job: 1-Provision Devel Cluster
      artifacts: true
  variables:
    TERRAFORM_ENV: devel

1-Provision Prod Cluster:
  extends: .provision_template
  stage: prod
  environment:
    name: prod
  variables:
    TERRAFORM_ENV: prod

2-Configure Prod Cluster:
  extends: .configure_template
  stage: prod
  environment:
    name: prod
  needs:
    - job: Provision Shared Resources
      artifacts: true
    - job: 1-Provision Prod Cluster
      artifacts: true
  variables:
    TERRAFORM_ENV: prod

1-Ubuntu Setup Playbook Devel Cluster (Optional):
  extends: .ubuntu_setup_template
  stage: optional
  environment:
    name: devel
  needs:
    - job: Provision Shared Resources
      artifacts: true
    - job: 1-Provision Devel Cluster
      artifacts: true
  variables:
    TERRAFORM_ENV: devel

2-Ubuntu Setup Playbook Prod Cluster (Optional):
  extends: .ubuntu_setup_template
  stage: optional
  environment:
    name: prod
  needs:
    - job: Provision Shared Resources
      artifacts: true
    - job: 1-Provision Prod Cluster
      artifacts: true
  variables:
    TERRAFORM_ENV: prod

#### Templates ####

.infra_template:
  tags:
    - msul-shared
  image: $CI_REGISTRY_IMAGE/ansible:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule" && $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
      when: manual
  before_script:
    # Setting up ssh key
    - eval $( ssh-agent -s )
    - echo "$ROOT_PRIVATE_KEY" | base64 -d | ssh-add -
    - install -d -m 700 ~/.ssh/
    - ( umask 022; touch ~/.ssh/known_hosts )
    - ssh-keyscan ansible.lib.msu.edu >> ~/.ssh/known_hosts

.provision_template:
  extends: .infra_template
  artifacts:
    paths:
      - configure-playbook/hosts
      - known_hosts
  script:
    - |
      # Copy the main.tf file into the correct location from the CI variable
      mv $MAIN_TF_FILE terraform/env/${TERRAFORM_ENV}/main.tf
      # Run the playbook to provision
      cat provision-playbook/variables.yml | envsubst | sponge provision-playbook/variables.yml;
      [[ -f terraform.tfvars.json ]] && mv terraform.tfvars.json terraform/env/${TERRAFORM_ENV}/;
      ansible-playbook provision-playbook/provision.yml;
      # artifacts must exist in current working directory
      cp /root/.ssh/known_hosts known_hosts;
      echo "Provisioning for $TERRAFORM_ENV completed.";

.ubuntu_setup_template:
  extends: .infra_template
  script:
    - |
      # Move artifact to correct location
      mv known_hosts ~/.ssh/known_hosts
      # Run the Ubuntu setup playbook
      if [[ $TERRAFORM_ENV == "devel" || $TERRAFORM_ENV == "prod" ]]; then
        scp configure-playbook/hosts ubuntusetup@ansible.lib.msu.edu:/home/ubuntusetup/hosts;
        ssh ubuntusetup@ansible.lib.msu.edu "sudo -Hu ansible /home/ubuntusetup/ubuntu-setup/add_host_keys /home/ubuntusetup/hosts";
        ssh ubuntusetup@ansible.lib.msu.edu "sudo -Hu ansible ansible-playbook -i /home/ubuntusetup/hosts /home/ubuntusetup/ubuntu-setup/runsetup.yml";
      fi

.configure_template:
  extends: .infra_template
  script:
    - |
      # Move artifact to correct location
      mv known_hosts ~/.ssh/known_hosts
      # Move CI variable file to correct location
      mv $VARIABLES_YAML_FILE configure-playbook/variables.yml
      # Run the configure playbook
      if [[ $TERRAFORM_ENV == "devel" || $TERRAFORM_ENV == "prod" ]]; then
        cat configure-playbook/variables.yml | envsubst | sponge configure-playbook/variables.yml;
        ansible-playbook configure-playbook/configure.yml -i configure-playbook/hosts;
        echo "Success! Servers for $TERRAFORM_ENV are now accessible.";
      fi

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
