---

- name: Ensure Samba is running and set to start on boot.
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true

- name: Copy the Customized smb.conf file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
  notify:
    - Restart Samba

- name: Copy the samba fail2ban config
  ansible.builtin.template:
    src: samba_filter.j2
    dest: /etc/fail2ban/filter.d/samba.conf

- name: Enable the samba fail2ban jail
  ansible.builtin.template:
    src: samba_jail.j2
    dest: /etc/fail2ban/jail.d/samba.conf
  notify:
    - Restart fail2ban

- name: Create Samba user group
  ansible.builtin.group:
    name: "{{ samba_group_user }}"
    state: present

- name: Create Samba users and add to Samba group
  ansible.builtin.user:
    name: "{{ samba_group_user }}"
    groups: "{{ samba_group_user }}"
    append: yes

- name: Create Samba Password for User(s)
  ansible.builtin.shell: "(echo {{ samba_pass }}; echo {{ samba_pass }}) | smbpasswd -s -a {{ samba_group_user }}"

- name: Allow Samba communication through UFW
  community.general.ufw:
    rule: allow
    from: 0.0.0.0/0
    proto: tcp
    port: 445

- name: Allow Samba alternate communication through UFW
  community.general.ufw:
    rule: allow
    from: 0.0.0.0/0
    proto: tcp
    port: 455

- name: Allow Samba client communication through UFW
  community.general.ufw:
    rule: allow
    from: 0.0.0.0/0
    proto: tcp
    port: 49152:65535
