---
- debug:
    msg: "{{ ansible_play_hosts_all.index(inventory_hostname) }}"

- name: Copy coreboot config
  ansible.builtin.template:
    src: roles/configure/templates/coreboot.j2
    dest: /etc/coreboot.cfg
    owner: root
    group: root
    mode: 0640
