---
version: "3.8"
services:
  badbot:
    image: registry.gitlab.msu.edu/msu-libraries/catalog/catalog-limited-access:latest
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        # Badbot limited access service
        - "traefik.http.services.badbot-limited.loadbalancer.server.port=80"
        # >> Tencent IP range with bots throughout: 43.128.0.0/10, 101.32.0.0/14, 123.206.0.0/15
        # >> chinamobile.com 117.48.148.0/22
        # >> China-based Alibaba Cloud Bot 47.76.0.0/16
        # >> some other bot from Singapore: 119.8.160.0/19, 124.243.128.0/18
        # >> spam bot from France: 45.95.233.103 (will probably not last)
        # >> sources of bot scanning with randomized/impossible user agents & absurd facet combos:
        #    - ethr.net: 69.176.80.0/20
        #    - China Mobile Communications: 223.64.0.0/10
        #    - China Mobile Communications: 36.128.0.0/10
        #    - China Mobile Communications: 111.0.0.0/10
        #    - China Mobile Communications: 120.192.0.0/10
        #    - China Mobile Communications: 39.128.0.0/10
        #    - China Mobile Communications: 183.192.0.0/10
        #    - China Mobile Communications: 112.0.0.0/10
        #    - China Mobile Communications: 117.128.0.0/10
        #    - CHINANET HUNAN PROVINCE NETWORK: 223.144.0.0/12
        #    - China Unicom Henan province network: 42.224.0.0/12
        #    - China Unicom Henan province network: 115.48.0.0/12
        #    - DE-SCALEIT-DELTA-23-1: 45.93.184.0/23
        #    - DE-SCALEIT-CHI-23-1: 45.89.148.0/23
        # >> Scanning every link on item pages repeatedly and quickly (citing, email, sms, export, etc)
        #    - Alibaba Cloud LLC: 47.82.8.0/22
        # >> Mass scraping print versions of EDS pages:
        #    - Zenlayer Cloud: 45.40.48.0/20
        # >> Very high load and suspicious outdated browser version conformity
        #    - Alibaba Cloud LLC: 47.80.0.0/13
        #    - Alibaba Cloud LLC: 47.76.0.0/14
        # >> Very distributed attack from individual IPs scattered across dozens of countries
        #    - UserAgent: Chrome/129.0.0.0 Safari/537.36
        # >> Very distributed attack from individual IPs scattered across dozens of countries with randomized user agents
        #    - Firefox/?. (Firefox version < 120)
        #    - Opera/?.
        #    - iPhone OS ?_  (iPhone OS < 10)
        #    - Gecko/????-   (Gecko build date > 2040)
        #    - MSIE ?.  (IE version < 10)
        #    - Windows 9?
        #    - Chrome/?.  (Chrome < 125)
        #    - Android ?.   (Android < 6)
        #    - Version/?.? Safari  (Old version of Safari)
        #    - PPC Mac OS X  (Ancient PPC Mac)
        #    - Windows NT ?.?   (Windows before version 10)
        #    - Trident ?.?    (Old IE Trident engine)
        #    - FxiOS ?.    (Firefox on iOS versions < 100)
        #    - CriOS ?.    (Chrome on iOS versions < 100)
        # >> Ramping up modulating bot scan from Huawei-Cloud
        #    - 1.92.0.0/16
        #    - 27.106.96.0/20
        #    - 46.250.168.0/21
        #    - 94.74.80.0/20
        #    - 94.74.96.0/20
        #    - 94.74.112.0/21
        #    - 94.74.120.0/21
        #    - 101.44.16.0/20
        #    - 101.46.0.0/20
        #    - 111.119.192.0/20
        #    - 111.119.208.0/20
        #    - 116.204.0.0/18
        #    - 116.204.64.0/18
        #    - 121.37.0.0/16
        #    - 121.91.168.0/22
        #    - 122.8.176.0/20
        #    - 159.138.0.0/16
        #    - 166.108.192.0/19
        #    - 189.1.224.0/19
        #    - 190.92.192.0/19
        # >> Spikes of very heavy load in unison from CN
        #    - 1.188.0.0/14
        #    - 8.208.0.0/12
        #    - 14.16.0.0/12
        #    - 14.144.0.0/12
        #    - 27.16.0.0/12
        #    - 27.152.0.0/17
        #    - 27.184.0.0/13
        #    - 27.192.0.0/11
        #    - 27.224.0.0/14
        #    - 42.52.0.0/14
        #    - 42.176.0.0/13
        #    - 49.64.0.0/11
        #    - 58.56.0.0/14
        #    - 58.244.0.0/15
        #    - 60.0.0.0/12
        #    - 60.16.0.0/13
        #    - 60.181.0.0/16
        #    - 60.208.0.0/12
        #    - 60.220.0.0/14
        #    - 101.16.0.0/12
        #    - 101.44.176.0/20
        #    - 101.72.0.0/14
        #    - 106.8.0.0/15
        #    - 106.112.0.0/13
        #    - 110.181.0.0/16
        #    - 110.240.0.0/12
        #    - 111.72.0.0/13
        #    - 111.85.0.0/16
        #    - 111.119.224.0/20
        #    - 111.160.0.0/13
        #    - 112.80.0.0/13
        #    - 112.96.0.0/15
        #    - 112.132.64.0/18
        #    - 112.224.0.0/11
        #    - 113.0.0.0/13
        #    - 113.27.0.0/19
        #    - 113.56.0.0/15
        #    - 113.64.0.0/11
        #    - 113.96.0.0/12
        #    - 113.112.0.0/13
        #    - 113.120.0.0/13
        #    - 113.136.0.0/13
        #    - 113.220.0.0/14
        #    - 113.224.0.0/12
        #    - 113.248.0.0/14
        #    - 114.96.0.0/13
        #    - 114.224.0.0/12
        #    - 114.240.0.0/12
        #    - 115.222.0.0/15
        #    - 116.8.0.0/14
        #    - 116.95.80.0/21
        #    - 116.128.0.0/10
        #    - 118.73.224.0/20
        #    - 119.13.80.0/21
        #    - 119.108.0.0/15
        #    - 119.128.0.0/12
        #    - 119.176.0.0/12
        #    - 120.0.0.0/12
        #    - 120.40.0.0/14
        #    - 120.80.0.0/13
        #    - 121.8.0.0/13
        #    - 121.16.0.0/13
        #    - 122.4.0.0/14
        #    - 122.96.0.0/15
        #    - 122.156.0.0/14
        #    - 122.240.0.0/16
        #    - 123.8.0.0/13
        #    - 123.52.0.0/14
        #    - 123.97.0.0/17
        #    - 123.128.0.0/13
        #    - 123.152.0.0/13
        #    - 123.168.0.0/14
        #    - 123.174.0.0/16
        #    - 124.76.0.0/14
        #    - 124.228.0.0/14
        #    - 124.234.0.0/15
        #    - 124.236.0.0/14
        #    - 124.240.0.0/17
        #    - 124.240.98.0/23
        #    - 139.202.0.0/16
        #    - 139.214.0.0/16
        #    - 144.255.0.0/16
        #    - 162.128.0.0/16
        #    - 166.108.192.0/18
        #    - 171.208.0.0/12
        #    - 175.30.0.0/15
        #    - 175.148.0.0/14
        #    - 175.160.0.0/12
        #    - 180.96.0.0/11
        #    - 180.152.0.0/13
        #    - 182.32.0.0/12
        #    - 182.112.0.0/12
        #    - 182.200.0.0/13
        #    - 182.240.0.0/13
        #    - 183.0.0.0/10
        #    - 183.128.0.0/12
        #    - 183.148.0.0/16
        #    - 183.156.0.0/14
        #    - 183.160.0.0/13
        #    - 183.191.224.0/20
        #    - 202.100.0.0/18
        #    - 218.7.0.0/14
        #    - 218.17.213.0/30
        #    - 218.24.0.0/15
        #    - 218.90.0.0/13
        #    - 219.128.0.0/12
        #    - 220.249.144.0/20
        #    - 221.192.0.0/14
        #    - 221.206.0.0/16
        #    - 221.216.0.0/13
        #    - 222.85.0.0/17
        #    - 222.92.0.0/14
        #    - 222.136.0.0/13
        #    - 222.240.0.0/13
        #    - 1.192.0.0/13
        #    - 112.100.0.0/14
        #    - 115.204.0.0/15
        #    - 116.78.0.0/15
        #    - 118.112.0.0/13
        #    - 119.112.0.0/13
        #    - 119.120.0.0/13
        #    - 123.184.0.0/14
        #    - 171.80.0.0/14
        #    - 211.141.160.0/17
        #    - 1.56.0.0/13
        #    - 1.202.0.0/15
        #    - 27.152.0.0/13
        #    - 36.32.0.0/14
        #    - 36.96.0.0/11
        #    - 42.63.0.0/16
        #    - 42.202.0.0/15
        #    - 58.17.0.0/17
        #    - 58.242.160.0/20
        #    - 58.248.0.0/13
        #    - 59.52.0.0/14
        #    - 61.159.128.0/18
        #    - 61.169.0.0/14
        #    - 101.64.0.0/13
        #    - 110.183.0.0/16
        #    - 112.88.0.0/13
        #    - 113.200.0.0/15
        #    - 114.104.0.0/14
        #    - 115.224.0.0/16
        #    - 115.229.0.0/16
        #    - 116.4.0.0/14
        #    - 116.207.0.0/16
        #    - 116.208.0.0/14
        #    - 117.40.0.0/14
        #    - 118.78.0.0/20
        #    - 118.80.96.0/20
        #    - 118.239.0.0/16
        #    - 119.62.0.0/16
        #    - 119.164.0.0/14
        #    - 119.248.0.0/14
        #    - 121.28.0.0/15
        #    - 121.32.0.0/14
        #    - 121.60.0.0/14
        #    - 121.224.0.0/12
        #    - 122.51.0.0/16
        #    - 122.224.0.0/12
        #    - 123.4.0.0/14
        #    - 123.101.0.0/16
        #    - 123.138.94.0/24
        #    - 123.139.168.0/24
        #    - 123.164.0.0/14
        #    - 124.128.0.0/13
        #    - 125.119.0.0/16
        #    - 139.209.0.0/16
        #    - 144.52.0.0/16
        #    - 180.160.0.0/12
        #    - 211.143.144.0/17
        #    - 218.7.0.0/14
        #    - 218.22.0.0/15
        #    - 218.27.0.0/16
        #    - 218.56.0.0/14
        #    - 219.154.0.0/14
        #    - 220.166.0.0/15
        #    - 221.207.64.0/16
        #    - 221.208.0.0/13
        #    - 223.11.0.0/16
        ### EXCEPTION: Chrome 116 allowed for Peter Berg
        # >> User-Agent bot matching: (?i) means case-insensitive match
        - "traefik.http.routers.badbot-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.badbot-https-router.rule=\
          ClientIP(`43.128.0.0/10`) || ClientIP(`117.48.148.0/22`) || ClientIP(`101.32.0.0/14`) || \
          ClientIP(`123.206.0.0/15`) || ClientIP(`47.76.0.0/16`) || ClientIP(`119.8.160.0/19`) || \
          ClientIP(`124.243.128.0/18`) || ClientIP(`45.95.233.103/32`) || ClientIP(`69.176.80.0/20`) || \
          ClientIP(`223.64.0.0/10`) || ClientIP(`36.128.0.0/10`) || ClientIP(`111.0.0.0/10`) || \
          ClientIP(`120.192.0.0/10`) || ClientIP(`39.128.0.0/10`) || ClientIP(`183.192.0.0/10`) || \
          ClientIP(`112.0.0.0/10`) || ClientIP(`117.128.0.0/10`) || ClientIP(`223.144.0.0/12`) || \
          ClientIP(`42.224.0.0/12`) || ClientIP(`115.48.0.0/12`) || \
          ClientIP(`45.93.184.0/23`) || ClientIP(`45.89.148.0/23`) || ClientIP(`45.40.48.0/20`) || \
          ClientIP(`47.82.8.0/22`) || ClientIP(`47.80.0.0/13`) || ClientIP(`47.76.0.0/14`) || \
          ClientIP(`1.92.0.0/16`) || \
          ClientIP(`27.106.96.0/20`) || ClientIP(`46.250.168.0/21`) || ClientIP(`94.74.80.0/20`) || \
          ClientIP(`94.74.96.0/20`) || ClientIP(`94.74.112.0/21`) || ClientIP(`94.74.120.0/21`) || \
          ClientIP(`101.44.16.0/20`) || ClientIP(`101.46.0.0/20`) || ClientIP(`111.119.192.0/20`) || \
          ClientIP(`111.119.208.0/20`) || ClientIP(`116.204.0.0/18`) || ClientIP(`116.204.64.0/18`) || \
          ClientIP(`121.37.0.0/16`) || ClientIP(`121.91.168.0/22`) || ClientIP(`122.8.176.0/20`) || \
          ClientIP(`159.138.0.0/16`) || ClientIP(`166.108.192.0/19`) || ClientIP(`189.1.224.0/19`) || \
          ClientIP(`190.92.192.0/19`) || \
          ClientIP(`1.188.0.0/14`) || ClientIP(`8.208.0.0/12`) || ClientIP(`14.16.0.0/12`) || \
          ClientIP(`14.144.0.0/12`) || ClientIP(`27.16.0.0/12`) || ClientIP(`27.152.0.0/17`) || \
          ClientIP(`27.184.0.0/13`) || ClientIP(`27.192.0.0/11`) || ClientIP(`27.224.0.0/14`) || \
          ClientIP(`42.52.0.0/14`) || ClientIP(`42.176.0.0/13`) || ClientIP(`49.64.0.0/11`) || \
          ClientIP(`58.56.0.0/14`) || ClientIP(`58.244.0.0/15`) || ClientIP(`60.0.0.0/12`) || \
          ClientIP(`60.16.0.0/13`) || ClientIP(`60.181.0.0/16`) || ClientIP(`60.208.0.0/12`) || \
          ClientIP(`60.220.0.0/14`) || ClientIP(`101.16.0.0/12`) || ClientIP(`101.44.176.0/20`) || \
          ClientIP(`101.72.0.0/14`) || ClientIP(`106.8.0.0/15`) || ClientIP(`106.112.0.0/13`) || \
          ClientIP(`110.181.0.0/16`) || ClientIP(`110.240.0.0/12`) || ClientIP(`111.72.0.0/13`) || \
          ClientIP(`111.85.0.0/16`) || ClientIP(`111.119.224.0/20`) || ClientIP(`111.160.0.0/13`) || \
          ClientIP(`112.80.0.0/13`) || ClientIP(`112.96.0.0/15`) || ClientIP(`112.132.64.0/18`) || \
          ClientIP(`112.224.0.0/11`) || ClientIP(`113.0.0.0/13`) || ClientIP(`113.27.0.0/19`) || \
          ClientIP(`113.56.0.0/15`) || ClientIP(`113.64.0.0/11`) || ClientIP(`113.96.0.0/12`) || \
          ClientIP(`113.112.0.0/13`) || ClientIP(`113.120.0.0/13`) || ClientIP(`113.136.0.0/13`) || \
          ClientIP(`113.220.0.0/14`) || ClientIP(`113.224.0.0/12`) || ClientIP(`113.248.0.0/14`) || \
          ClientIP(`114.96.0.0/13`) || ClientIP(`114.224.0.0/12`) || ClientIP(`114.240.0.0/12`) || \
          ClientIP(`115.222.0.0/15`) || ClientIP(`116.8.0.0/14`) || ClientIP(`116.95.80.0/21`) || \
          ClientIP(`116.128.0.0/10`) || ClientIP(`118.73.224.0/20`) || ClientIP(`119.13.80.0/21`) || \
          ClientIP(`119.108.0.0/15`) || ClientIP(`119.128.0.0/12`) || ClientIP(`119.176.0.0/12`) || \
          ClientIP(`120.0.0.0/12`) || ClientIP(`120.40.0.0/14`) || ClientIP(`120.80.0.0/13`) || \
          ClientIP(`121.8.0.0/13`) || ClientIP(`121.16.0.0/13`) || ClientIP(`122.4.0.0/14`) || \
          ClientIP(`122.96.0.0/15`) || ClientIP(`122.156.0.0/14`) || ClientIP(`122.240.0.0/16`) || \
          ClientIP(`123.8.0.0/13`) || ClientIP(`123.52.0.0/14`) || ClientIP(`123.97.0.0/17`) || \
          ClientIP(`123.128.0.0/13`) || ClientIP(`123.152.0.0/13`) || ClientIP(`123.168.0.0/14`) || \
          ClientIP(`123.174.0.0/16`) || ClientIP(`124.76.0.0/14`) || ClientIP(`124.228.0.0/14`) || \
          ClientIP(`124.234.0.0/15`) || ClientIP(`124.236.0.0/14`) || ClientIP(`124.240.0.0/17`) || \
          ClientIP(`124.240.98.0/23`) || ClientIP(`139.202.0.0/16`) || ClientIP(`139.214.0.0/16`) || \
          ClientIP(`144.255.0.0/16`) || ClientIP(`162.128.0.0/16`) || ClientIP(`166.108.192.0/18`) || \
          ClientIP(`171.208.0.0/12`) || ClientIP(`175.30.0.0/15`) || ClientIP(`175.148.0.0/14`) || \
          ClientIP(`175.160.0.0/12`) || ClientIP(`180.96.0.0/11`) || ClientIP(`180.152.0.0/13`) || \
          ClientIP(`182.32.0.0/12`) || ClientIP(`182.112.0.0/12`) || ClientIP(`182.200.0.0/13`) || \
          ClientIP(`182.240.0.0/13`) || ClientIP(`183.0.0.0/10`) || ClientIP(`183.128.0.0/12`) || \
          ClientIP(`183.148.0.0/16`) || ClientIP(`183.156.0.0/14`) || ClientIP(`183.160.0.0/13`) || \
          ClientIP(`183.191.224.0/20`) || ClientIP(`202.100.0.0/18`) || ClientIP(`218.7.0.0/14`) || \
          ClientIP(`218.17.213.0/30`) || ClientIP(`218.24.0.0/15`) || ClientIP(`218.90.0.0/13`) || \
          ClientIP(`219.128.0.0/12`) || ClientIP(`220.249.144.0/20`) || ClientIP(`221.192.0.0/14`) || \
          ClientIP(`221.206.0.0/16`) || ClientIP(`221.216.0.0/13`) || ClientIP(`222.85.0.0/17`) || \
          ClientIP(`222.92.0.0/14`) || ClientIP(`222.136.0.0/13`) || ClientIP(`222.240.0.0/13`) || \
          ClientIP(`1.192.0.0/13`) || ClientIP(`112.100.0.0/14`) || ClientIP(`115.204.0.0/15`) || \
          ClientIP(`116.78.0.0/15`) || ClientIP(`118.112.0.0/13`) || ClientIP(`119.112.0.0/13`) || \
          ClientIP(`119.120.0.0/13`) || ClientIP(`123.184.0.0/14`) || ClientIP(`171.80.0.0/14`) || \
          ClientIP(`211.141.160.0/17`) || \
          ClientIP(`1.56.0.0/13`) || ClientIP(`1.202.0.0/15`) || ClientIP(`27.152.0.0/13`) || \
          ClientIP(`36.32.0.0/14`) || ClientIP(`36.96.0.0/11`) || ClientIP(`42.63.0.0/16`) || \
          ClientIP(`42.202.0.0/15`) || ClientIP(`58.17.0.0/17`) || ClientIP(`58.242.160.0/20`) || \
          ClientIP(`58.248.0.0/13`) || ClientIP(`59.52.0.0/14`) || ClientIP(`61.159.128.0/18`) || \
          ClientIP(`61.169.0.0/14`) || ClientIP(`101.64.0.0/13`) || ClientIP(`110.183.0.0/16`) || \
          ClientIP(`112.88.0.0/13`) || ClientIP(`113.200.0.0/15`) || ClientIP(`114.104.0.0/14`) || \
          ClientIP(`115.224.0.0/16`) || ClientIP(`115.229.0.0/16`) || ClientIP(`116.4.0.0/14`) || \
          ClientIP(`116.207.0.0/16`) || ClientIP(`116.208.0.0/14`) || ClientIP(`117.40.0.0/14`) || \
          ClientIP(`118.78.0.0/20`) || ClientIP(`118.80.96.0/20`) || ClientIP(`118.239.0.0/16`) || \
          ClientIP(`119.62.0.0/16`) || ClientIP(`119.164.0.0/14`) || ClientIP(`119.248.0.0/14`) || \
          ClientIP(`121.28.0.0/15`) || ClientIP(`121.32.0.0/14`) || ClientIP(`121.60.0.0/14`) || \
          ClientIP(`121.224.0.0/12`) || ClientIP(`122.51.0.0/16`) || ClientIP(`122.224.0.0/12`) || \
          ClientIP(`123.4.0.0/14`) || ClientIP(`123.101.0.0/16`) || ClientIP(`123.138.94.0/24`) || \
          ClientIP(`123.139.168.0/24`) || ClientIP(`123.164.0.0/14`) || ClientIP(`124.128.0.0/13`) || \
          ClientIP(`125.119.0.0/16`) || ClientIP(`139.209.0.0/16`) || ClientIP(`144.52.0.0/16`) || \
          ClientIP(`180.160.0.0/12`) || ClientIP(`211.143.144.0/17`) || ClientIP(`218.7.0.0/14`) || \
          ClientIP(`218.22.0.0/15`) || ClientIP(`218.27.0.0/16`) || ClientIP(`218.56.0.0/14`) || \
          ClientIP(`219.154.0.0/14`) || ClientIP(`220.166.0.0/15`) || ClientIP(`221.207.64.0/16`) || \
          ClientIP(`221.208.0.0/13`) || ClientIP(`223.11.0.0/16`) || \
          HeadersRegexp(`User-Agent`, `Firefox/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `Firefox/1[0-1][0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `Opera/[0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `iPhone OS [0-9]_`) || \
          HeadersRegexp(`User-Agent`, `Gecko/1[0-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/20[4-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/2[1-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/[03-9][0-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `MSIE [0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `Windows 9[5-8x]`) || \
          HeadersRegexp(`User-Agent`, `Chrome/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `Chrome/1[0-1][0-5]\\.`) || \
          HeadersRegexp(`User-Agent`, `Chrome/1[0-1][7-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `Chrome/12[0-4]\\.`) || \
          HeadersRegexp(`User-Agent`, `Android [1-6]\\.`) || \
          HeadersRegexp(`User-Agent`, `Version/[0-9]\\.[0-9](\\.[0-9])? Safari`) || \
          HeadersRegexp(`User-Agent`, `FxiOS/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `CriOS/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `PPC Mac OS X`) || \
          HeadersRegexp(`User-Agent`, `Windows NT [0-9]\\.[0-9]`) || \
          HeadersRegexp(`User-Agent`, `Trident [0-9]\\.[0-9]`) || \
          HeadersRegexp(`User-Agent`, `(?i)(Bytespider|AcademicBotRTU|GoogleOther|Amazonbot|ClaudeBot|GPTBot|FriendlyCrawler|SemrushBot|Diffbot|HawaiiBot|DataForSeoBot)`) || \
          HeadersRegexp(`User-Agent`, `Chrome/129\\.0\\.0\\.0 Safari/537\\.36`)"
        - "traefik.http.routers.badbot-https-router.priority=10000"
        - "traefik.http.routers.badbot-https-router.tls=true"
        - "traefik.http.routers.badbot-https-router.service=badbot-limited"

networks:
  public:
    name: public
    external: true
