---
version: "3.8"

services:
  prune-nodes:
    image: docker
    # Need the sleep so Docker has enough time to add networking to the container
    # to not consider this a failed task and roll back deploys
    command: ["sh", "-c", "docker system prune -a -f --filter until=30m; sleep 10;"]
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "var_lib_docker:/var/lib/docker"
    deploy:
      mode: global
      restart_policy:
        delay: 30m
      update_config:
        failure_action: rollback
      resources:
        limits:
          cpus: '0.50'
          memory: 50M

networks:
  public:
    name: public
    external: true

volumes:
  var_lib_docker:
