---
version: "3.8"
services:
  badbot:
    image: ${BADBOTS_IMAGE}
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        window: 15s

networks:
  public:
    name: public
    external: true
