---
version: "3.8"
services:
  dummy:
    image: busybox:latest
    command: sleep inf
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        # Avoid processing requests from bots
        - "traefik.http.middlewares.badbot-block.ipallowlist.sourcerange=127.0.0.1/32"
        # Badbot bouncer dummy service
        - "traefik.http.services.badbot-bouncer.loadbalancer.server.port=9999"
        # Badbot HTTP
        - "traefik.http.routers.badbot-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.badbot-http-router.middlewares=badbot-block"
        # >> Tencent IP range with bots throughout: 43.128.0.0/10, 101.32.0.0/14, 123.206.0.0/15
        # >> chinamobile.com 117.48.148.0/22
        # >> China-based Alibaba Cloud Bot 47.76.0.0/16
        # >> some other bot from Singapore: 119.8.160.0/19, 124.243.128.0/18
        # >> spam bot from France: 45.95.233.103 (will probably not last)
        # >> sources of bot scanning with randomized/impossible user agents & absurd facet combos:
        #    - ethr.net: 69.176.80.0/20
        #    - China Mobile Communications: 223.64.0.0/10
        #    - China Mobile Communications: 36.128.0.0/10
        #    - China Mobile Communications: 111.0.0.0/10
        #    - China Mobile Communications: 120.192.0.0/10
        #    - China Mobile Communications: 39.128.0.0/10
        #    - China Mobile Communications: 183.192.0.0/10
        #    - China Mobile Communications: 112.0.0.0/10
        #    - China Mobile Communications: 117.128.0.0/10
        #    - CHINANET HUNAN PROVINCE NETWORK: 223.144.0.0/12
        #    - China Unicom Henan province network: 42.224.0.0/12
        #    - China Unicom Henan province network: 115.48.0.0/12
        #    - DE-SCALEIT-DELTA-23-1: 45.93.184.0/23
        #    - DE-SCALEIT-CHI-23-1: 45.89.148.0/23
        # >> User-Agent bot matching: (?i) means case-insensitive match
        - "traefik.http.routers.badbot-http-router.rule=\
          ClientIP(`43.128.0.0/10`) || ClientIP(`117.48.148.0/22`) || ClientIP(`101.32.0.0/14`) || \
          ClientIP(`123.206.0.0/15`) || ClientIP(`47.76.0.0/16`) || ClientIP(`119.8.160.0/19`) || \
          ClientIP(`124.243.128.0/18`) || ClientIP(`45.95.233.103/32`) || ClientIP(`69.176.80.0/20`) || \
          ClientIP(`223.64.0.0/10`) || ClientIP(`36.128.0.0/10`) || ClientIP(`111.0.0.0/10`) || \
          ClientIP(`120.192.0.0/10`) || ClientIP(`39.128.0.0/10`) || ClientIP(`183.192.0.0/10`) || \
          ClientIP(`112.0.0.0/10`) || ClientIP(`117.128.0.0/10`) || ClientIP(`223.144.0.0/12`) || \
          ClientIP(`42.224.0.0/12`) || ClientIP(`115.48.0.0/12`) || \
          ClientIP(`45.93.184.0/23`) || ClientIP(`45.89.148.0/23`) || \
          HeadersRegexp(`User-Agent`, `(?i)(Bytespider|AcademicBotRTU|GoogleOther|Amazonbot|ClaudeBot|GPTBot|FriendlyCrawler|SemrushBot|Diffbot|HawaiiBot|DataForSeoBot)`)"
        - "traefik.http.routers.badbot-http-router.priority=10000"
        - "traefik.http.routers.badbot-http-router.service=badbot-bouncer"
        # Badbot HTTPS
        - "traefik.http.routers.badbot-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.badbot-https-router.middlewares=badbot-block"
        - "traefik.http.routers.badbot-https-router.rule=\
          ClientIP(`43.128.0.0/10`) || ClientIP(`117.48.148.0/22`) || ClientIP(`101.32.0.0/14`) || \
          ClientIP(`123.206.0.0/15`) || ClientIP(`47.76.0.0/16`) || ClientIP(`119.8.160.0/19`) || \
          ClientIP(`124.243.128.0/18`) || ClientIP(`45.95.233.103/32`) || ClientIP(`69.176.80.0/20`) || \
          ClientIP(`223.64.0.0/10`) || ClientIP(`36.128.0.0/10`) || ClientIP(`111.0.0.0/10`) || \
          ClientIP(`120.192.0.0/10`) || ClientIP(`39.128.0.0/10`) || ClientIP(`183.192.0.0/10`) || \
          ClientIP(`112.0.0.0/10`) || ClientIP(`117.128.0.0/10`) || ClientIP(`223.144.0.0/12`) || \
          ClientIP(`42.224.0.0/12`) || ClientIP(`115.48.0.0/12`) || \
          ClientIP(`45.93.184.0/23`) || ClientIP(`45.89.148.0/23`) || \
          HeadersRegexp(`User-Agent`, `(?i)(Bytespider|AcademicBotRTU|GoogleOther|Amazonbot|ClaudeBot|GPTBot|FriendlyCrawler|SemrushBot|Diffbot|HawaiiBot|DataForSeoBot)`)"
        - "traefik.http.routers.badbot-https-router.priority=10000"
        - "traefik.http.routers.badbot-https-router.tls=true"
        - "traefik.http.routers.badbot-https-router.service=badbot-bouncer"

networks:
  public:
    name: public
    external: true
