---
version: "3.8"

services:
  prune-nodes:
    image: docker
    command: ["docker", "system", "prune", "-a", "-f", "--filter", "until=30m"]
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "var_lib_docker:/var/lib/docker"
    deploy:
      mode: global
      restart_policy:
        delay: 30m
      update_config:
        failure_action: rollback

networks:
  public:
    name: public
    external: true

volumes:
  var_lib_docker:
