---
services:
  pages:
    image: ${NO_ACCESS_IMAGE}
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.static-pages.loadbalancer.server.port=80"
        # Dummy router as to prevent default router being added
        - "traefik.http.routers.no-access-dummy-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.no-access-dummy-router.tls=true"
        - "traefik.http.routers.no-access-dummy-router.rule=ClientIP(`127.0.254.254`)"

networks:
  public:
    name: public
    external: true
