---
version: "3.8"
services:
  badbot:
    image: registry.gitlab.msu.edu/msu-libraries/catalog/catalog-limited-access:latest
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        # Badbot limited access service
        - "traefik.http.services.badbot-limited.loadbalancer.server.port=80"
        # >> Tencent IP range with bots throughout: 43.128.0.0/10, 101.32.0.0/14, 123.206.0.0/15
        # >> chinamobile.com 117.48.148.0/22
        # >> China-based Alibaba Cloud Bot 47.76.0.0/16
        # >> some other bot from Singapore: 119.8.160.0/19, 124.243.128.0/18
        # >> spam bot from France: 45.95.233.103 (will probably not last)
        # >> sources of bot scanning with randomized/impossible user agents & absurd facet combos:
        #    - ethr.net: 69.176.80.0/20
        #    - China Mobile Communications: 223.64.0.0/10
        #    - China Mobile Communications: 36.128.0.0/10
        #    - China Mobile Communications: 111.0.0.0/10
        #    - China Mobile Communications: 120.192.0.0/10
        #    - China Mobile Communications: 39.128.0.0/10
        #    - China Mobile Communications: 183.192.0.0/10
        #    - China Mobile Communications: 112.0.0.0/10
        #    - China Mobile Communications: 117.128.0.0/10
        #    - CHINANET HUNAN PROVINCE NETWORK: 223.144.0.0/12
        #    - China Unicom Henan province network: 42.224.0.0/12
        #    - China Unicom Henan province network: 115.48.0.0/12
        #    - DE-SCALEIT-DELTA-23-1: 45.93.184.0/23
        #    - DE-SCALEIT-CHI-23-1: 45.89.148.0/23
        # >> Scanning every link on item pages repeatedly and quickly (citing, email, sms, export, etc)
        #    - Alibaba Cloud LLC: 47.82.8.0/22
        # >> Very high load and suspicious outdated browser version conformity
        #    - Alibaba Cloud LLC: 47.80.0.0/13
        #    - Alibaba Cloud LLC: 47.76.0.0/14
        # >> Very distributed attack from individual IPs scattered across dozens of countries
        #    - UserAgent: Chrome/129.0.0.0 Safari/537.36
        # >> Very distributed attack from individual IPs scattered across dozens of countries with randomized user agents
        #    - Firefox/?. Firefox/??. (Firefox version < 100)
        #    - Opera/?.
        #    - iPhone OS ?_  (iPhone OS < 10)
        #    - Gecko/????-   (Gecko build date > 2040)
        #    - MSIE ?.  (IE version < 10)
        #    - Windows 9?
        #    - Chrome/??.  (Chrome < 125)
        #    - Android ?.   (Android < 6)
        #    - Version/?.? Safari  (Old version of Safari)
        #    - PPC Mac OS X  (Ancient PPC Mac)
        #    - Windows NT ?.?   (Windows before version 10)
        #    - Trident ?.?    (Old IE Trident engine)
        #    - FxiOS ?.    (Firefox on iOS versions < 100)
        #    - CriOS ?.    (Chrome on iOS versions < 100)
        # >> Ramping up modulating bot scan from Huawei-Cloud
        #    - 27.106.96.0/20
        #    - 46.250.168.0/21
        #    - 94.74.80.0/20
        #    - 94.74.96.0/20
        #    - 94.74.112.0/21
        #    - 94.74.120.0/21
        #    - 101.44.16.0/20
        #    - 101.46.0.0/20
        #    - 111.119.192.0/20
        #    - 111.119.208.0/20
        #    - 121.91.168.0/22
        #    - 122.8.176.0/20
        #    - 159.138.0.0/16
        #    - 166.108.192.0/19
        #    - 189.1.224.0/19
        #    - 190.92.192.0/19
        # >> User-Agent bot matching: (?i) means case-insensitive match
        - "traefik.http.routers.badbot-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.badbot-https-router.rule=\
          ClientIP(`43.128.0.0/10`) || ClientIP(`117.48.148.0/22`) || ClientIP(`101.32.0.0/14`) || \
          ClientIP(`123.206.0.0/15`) || ClientIP(`47.76.0.0/16`) || ClientIP(`119.8.160.0/19`) || \
          ClientIP(`124.243.128.0/18`) || ClientIP(`45.95.233.103/32`) || ClientIP(`69.176.80.0/20`) || \
          ClientIP(`223.64.0.0/10`) || ClientIP(`36.128.0.0/10`) || ClientIP(`111.0.0.0/10`) || \
          ClientIP(`120.192.0.0/10`) || ClientIP(`39.128.0.0/10`) || ClientIP(`183.192.0.0/10`) || \
          ClientIP(`112.0.0.0/10`) || ClientIP(`117.128.0.0/10`) || ClientIP(`223.144.0.0/12`) || \
          ClientIP(`42.224.0.0/12`) || ClientIP(`115.48.0.0/12`) || \
          ClientIP(`45.93.184.0/23`) || ClientIP(`45.89.148.0/23`) || \
          ClientIP(`47.82.8.0/22`) || ClientIP(`47.80.0.0/13`) || ClientIP(`47.76.0.0/14`) || \
          ClientIP(`27.106.96.0/20`) || ClientIP(`46.250.168.0/21`) || ClientIP(`94.74.80.0/20`) || \
          ClientIP(`94.74.96.0/20`) || ClientIP(`94.74.112.0/21`) || ClientIP(`94.74.120.0/21`) || \
          ClientIP(`101.44.16.0/20`) || ClientIP(`101.46.0.0/20`) || ClientIP(`111.119.192.0/20`) || \
          ClientIP(`111.119.208.0/20`) || ClientIP(`121.91.168.0/22`) || ClientIP(`122.8.176.0/20`) || \
          ClientIP(`159.138.0.0/16`) || ClientIP(`166.108.192.0/19`) || ClientIP(`189.1.224.0/19`) || \
          ClientIP(`190.92.192.0/19`) || \
          HeadersRegexp(`User-Agent`, `Firefox/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `Opera/[0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `iPhone OS [0-9]_`) || \
          HeadersRegexp(`User-Agent`, `Gecko/1[0-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/20[4-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/2[1-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `Gecko/[03-9][0-9][0-9][0-9]-`) || \
          HeadersRegexp(`User-Agent`, `MSIE [0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `Windows 9[5-8x]`) || \
          HeadersRegexp(`User-Agent`, `Chrome/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `Chrome/1[0-1][0-9]\\.`) || \
          HeadersRegexp(`User-Agent`, `Chrome/12[0-4]\\.`) || \
          HeadersRegexp(`User-Agent`, `Android [1-6]\\.`) || \
          HeadersRegexp(`User-Agent`, `Version/[0-9]\\.[0-9] Safari`) || \
          HeadersRegexp(`User-Agent`, `FxiOS/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `CriOS/[0-9]{1,2}\\.`) || \
          HeadersRegexp(`User-Agent`, `PPC Mac OS X`) || \
          HeadersRegexp(`User-Agent`, `Windows NT [0-9]\\.[0-9]`) || \
          HeadersRegexp(`User-Agent`, `Trident [0-9]\\.[0-9]`) || \
          HeadersRegexp(`User-Agent`, `(?i)(Bytespider|AcademicBotRTU|GoogleOther|Amazonbot|ClaudeBot|GPTBot|FriendlyCrawler|SemrushBot|Diffbot|HawaiiBot|DataForSeoBot)`) || \
          HeadersRegexp(`User-Agent`, `Chrome/129\\.0\\.0\\.0 Safari/537\\.36`)"
        - "traefik.http.routers.badbot-https-router.priority=10000"
        - "traefik.http.routers.badbot-https-router.tls=true"
        - "traefik.http.routers.badbot-https-router.service=badbot-limited"

networks:
  public:
    name: public
    external: true
