---

- name: Configure catalog servers
  hosts: catalog_nodes
  gather_facts: true
  
  vars_files:
    - variables.yml

  roles:
    - install-dependencies
    - configure-coreboot
    - configure-ssh
    - mount-shared-storage
    - configure-swarm
    - configure-email
    - saml-setup
    - deploy-variables
    - restrict-ubuntu-user
    - ncpa-plugins

  tasks:
    - name: Create users
      include_role:
        name: setup-users
      loop: "{{ create_users }}"
      loop_control:
        loop_var: user_dict
        label: "{{ user_dict.comment }}"

- name: Call coreboot playbook
  ansible.builtin.import_playbook: playbook-conditional-reboot/playbook-setup-only.yml
