---

- name: Configure catalog servers
  hosts: catalog_nodes
  gather_facts: true
  
  vars_files:
    - variables.yml

  roles:
    - install-dependencies
    - configure-conreboot
    - configure-updates
    - configure-ssh
    - mount-shared-storage
    - configure-swarm
    - configure-email
    - saml-setup
    - deploy-variables
    - restrict-ubuntu-user
    - ncpa-plugins
    - configure-logrotate
    - grant-permissions
    - deploy-helper-scripts

  tasks:
    - name: Create users
      include_role:
        name: setup-users
      loop: "{{ create_users }}"
      loop_control:
        loop_var: user_dict
        label: "{{ user_dict.comment }}"
    - name: Deploy docker core stacks
      # Must occur after create users
      include_role:
        name: core-stacks
