---

- name: Configure catalog servers
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  remote_user: ansible
  
  vars_files:
    - variables.yml

  roles:
    - install-dependencies

  tasks:
    - name: Create users
      include_role:
        name: setup-users
      loop: "{{ create_users }}"
      loop_control:
        loop_var: user_dict
        label: "{{ user_dict.comment }}"

- name: Call setup playbook
  ansible.builtin.import_playbook: playbook-ubuntu-setup/runsetup.yml
