---

- name: Install conreboot
  ansible.builtin.apt:
    deb: "https://github.com/MSU-Libraries/conreboot/releases/download/{{CONREBOOT_VERSION}}/conreboot-{{CONREBOOT_VERSION}}.deb"
  when:
  - CONREBOOT_VERSION is defined
  - CONREBOOT_VERSION != ''

- name: Copy conreboot config
  ansible.builtin.template:
    src: conreboot.j2
    dest: /etc/conreboot.cfg
    owner: root
    group: root
    mode: '0644'
  tags:
    - configure-conreboot
  when:
  - CONREBOOT_VERSION is defined
  - CONREBOOT_VERSION != ''
