---

# TODO goofys can be removed if EFS works out
- name: Download Goofys binary
  ansible.builtin.get_url:
    url: https://github.com/kahing/goofys/releases/latest/download/goofys
    dest: /usr/local/bin/goofys
    mode: '0711'

- name: Make directory for mounting
  ansible.builtin.file:
    path: /mnt/shared
    state: directory
    mode: '0755'

- name: Create /etc/fstab entry
  ansible.posix.mount:
    path: /mnt/shared
    src: goofys#msulib-catalog-shared
    state: mounted
    fstype: fuse
    opts: _netdev,allow_other,--file-mode=0664,--dir-mode=0775

- name: Make directory for EFS mount
  ansible.builtin.file:
    path: /mnt/efs_catalog
    state: directory
    mode: '0755'

- name: Mount for EFS storage in /etc/fstab
  ansible.posix.mount:
    path: /mnt/efs_catalog
    src: "{{ efs_hostname }}:/"
    state: mounted
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev
