---

- name: Make directory for EFS mount
  ansible.builtin.file:
    path: /mnt/shared
    state: directory
    mode: '0755'

- name: Mount for EFS storage in /etc/fstab
  ansible.posix.mount:
    path: /mnt/shared
    src: "{{ efs_hostname }}:/"
    state: mounted
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev
