---

- name: Create directories for SAML key/cert generation
  ansible.builtin.file:
    path: "samlcerts/{{ item }}"
    state: directory
    owner: root
    group: www-data
    mode: '0755'
  loop:
    - devel-authentication
    - catalog-beta
    - catalog-prod
    - catalog-preview
  delegate_to: 127.0.0.1
  run_once: true

- name: Create new private keys for SAML
  community.crypto.openssl_privatekey:
    path: "samlcerts/{{ item }}/sp-private.pem"
    group: www-data
    mode: '0640'
  loop:
    - devel-authentication
    - catalog-beta
    - catalog-prod
    - catalog-preview
  delegate_to: 127.0.0.1
  run_once: true

- name: Create CSR for SAML certs
  community.crypto.openssl_csr:
    path: "samlcerts/{{ item }}/sp.csr"
    privatekey_path: "samlcerts/{{ item }}/sp-private.pem"
    country_name: US
    organization_name: Michigan State University Libraries
    common_name: catalog.lib.msu.edu
    subject_alt_name: "DNS:catalog-prod.lib.msu.edu,DNS:catalog-beta.lib.msu.edu,DNS:devel-authentication.lib.msu.edu,DNS:catalog-preview.lib.msu.edu"
  loop:
    - devel-authentication
    - catalog-beta
    - catalog-prod
    - catalog-preview
  delegate_to: 127.0.0.1
  run_once: true

- name: Create new certs for SAML
  community.crypto.x509_certificate:
    path: "samlcerts/{{ item }}/sp.crt"
    privatekey_path: "samlcerts/{{ item }}/sp-private.pem"
    csr_path: "samlcerts/{{ item }}/sp.csr"
    provider: selfsigned
  loop:
    - devel-authentication
    - catalog-beta
    - catalog-prod
    - catalog-preview
  delegate_to: 127.0.0.1
  run_once: true

- name: Copy SAML keys/certs to hosts
  ansible.builtin.copy:
    src: samlcerts/
    dest: /home/deploy/samlcerts/
    owner: root
    group: www-data
    mode: preserve
    directory_mode: '0755'
