---

- name: Create directories for SAML key/cert generation
  ansible.builtin.file:
    path: "/tmp/samlcerts/{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - test
    - qa
    - prod
  delegate_to: 127.0.0.1
  run_once: true

- name: Create new private keys for SAML
  community.crypto.openssl_privatekey:
    path: "/tmp/samlcerts/{{ item }}/sp-private.pem"
  loop:
    - test
    - qa
    - prod
  delegate_to: 127.0.0.1
  run_once: true

- name: Generate public keys for SAML
  community.crypto.openssl_publickey:
    path: "/tmp/samlcerts/{{ item }}/sp-public.pem"
    privatekey_path: "/tmp/samlcerts/{{ item }}/sp-private.pem"
  loop:
    - test
    - qa
    - prod
  delegate_to: 127.0.0.1
  run_once: true

- name: Create new certs for SAML
  community.crypto.openssh_cert:
    type: host
    signing_key: "/tmp/samlcerts/{{ item }}/sp-private.pem"
    public_key: "/tmp/samlcerts/{{ item }}/sp-public.pem"
    path: "/tmp/samlcerts/{{ item }}/sp.crt"
    valid_from: +0s
    valid_to: +400w
  loop:
    - test
    - qa
    - prod
  delegate_to: 127.0.0.1
  run_once: true

- name: Copy SAML keys/certs to hosts
  ansible.builtin.copy:
    src: /tmp/samlcerts/
    dest: /home/deploy/samlcerts/
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0750'
